# Render.com Web Service Configuration

services:
  - type: web
    name: vectorise-me-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: RUST_LOG
        value: info
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
        # Replace with your actual Vercel frontend URL
    autoDeploy: true
